services:
  # Backend Service
  - type: web
    name: tunorth-brms-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: singapore
    healthCheckPath: /health
    
