services:
  # Backend Service
  - type: web
    name: TUNorth-BRMS_BACKEND
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: singapore
    healthCheckPath: /health
    
